sonar.projectKey=tropical-management-v1
sonar.projectName=Tropical Management V1
sonar.sources=services,internal,web/app,web/components,web/lib
sonar.exclusions=**/node_modules/**,**/.next/**
sonar.sourceEncoding=UTF-8
