package main

import (
	"database/sql"
	"log"
	"net/http"
	"time"

	"github.com/ditasetyakurniawan-droid/tropical-management-v1/internal/dbx"
	"github.com/ditasetyakurniawan-droid/tropical-management-v1/internal/httpx"
)

type app struct{ db *sql.DB }
type item struct { ID int64 `json:"id"`; SKU string `json:"sku"`; Name string `json:"name"`; Unit string `json:"unit"`; Stock float64 `json:"stock"`; ReorderLevel float64 `json:"reorder_level"`; SupplierID int64 `json:"supplier_id"`; UpdatedAt time.Time `json:"updated_at"` }
type supplier struct { ID int64 `json:"id"`; Name string `json:"name"`; Contact string `json:"contact"`; Phone string `json:"phone"` }

func main(){ db,err:=dbx.Open(httpx.Env("INVENTORY_DB_DSN","tropical:tropical@tcp(mysql:3306)/tropical_inventory?parseTime=true&charset=utf8mb4")); if err!=nil{log.Fatal(err)}; defer db.Close(); a:=&app{db:db}; if err:=a.migrate();err!=nil{log.Fatal(err)}; mux:=http.NewServeMux(); mux.HandleFunc("/healthz",func(w http.ResponseWriter,_ *http.Request){httpx.JSON(w,200,map[string]string{"status":"ok","service":"inventory-service"})}); mux.HandleFunc("/api/inventory",a.inventory); mux.HandleFunc("/api/inventory/adjust",a.adjust); mux.HandleFunc("/api/suppliers",a.suppliers); mux.HandleFunc("/internal/summary",a.summary); log.Println("inventory-service listening on :8080"); log.Fatal(http.ListenAndServe(":8080",mux)) }
func(a *app)migrate()error{ qs:=[]string{`CREATE TABLE IF NOT EXISTS suppliers(id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(160) NOT NULL,contact VARCHAR(160),phone VARCHAR(60),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,`CREATE TABLE IF NOT EXISTS inventory_items(id BIGINT PRIMARY KEY AUTO_INCREMENT,sku VARCHAR(80) NOT NULL UNIQUE,name VARCHAR(180) NOT NULL,unit VARCHAR(40) NOT NULL,stock DECIMAL(12,2) NOT NULL DEFAULT 0,reorder_level DECIMAL(12,2) NOT NULL DEFAULT 0,supplier_id BIGINT NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_stock(stock)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`}; for _,q:=range qs{if _,err:=a.db.Exec(q);err!=nil{return err}}; return nil }
func(a *app)inventory(w http.ResponseWriter,r *http.Request){switch r.Method{case http.MethodGet: rows,err:=a.db.Query("SELECT id,sku,name,unit,stock,reorder_level,COALESCE(supplier_id,0),updated_at FROM inventory_items ORDER BY name"); if err!=nil{httpx.JSON(w,500,map[string]string{"error":err.Error()});return}; defer rows.Close(); out:=[]item{}; for rows.Next(){var x item;if rows.Scan(&x.ID,&x.SKU,&x.Name,&x.Unit,&x.Stock,&x.ReorderLevel,&x.SupplierID,&x.UpdatedAt)==nil{out=append(out,x)}};httpx.JSON(w,200,out);case http.MethodPost:var x item;if httpx.DecodeJSON(r,&x)!=nil{httpx.JSON(w,400,map[string]string{"error":"invalid json"});return};res,err:=a.db.Exec("INSERT INTO inventory_items(sku,name,unit,stock,reorder_level,supplier_id) VALUES(?,?,?,?,?,NULLIF(?,0))",x.SKU,x.Name,x.Unit,x.Stock,x.ReorderLevel,x.SupplierID);if err!=nil{httpx.JSON(w,409,map[string]string{"error":"sku already exists or invalid data"});return};x.ID,_=res.LastInsertId();x.UpdatedAt=time.Now();httpx.JSON(w,201,x);default:httpx.JSON(w,405,map[string]string{"error":"method not allowed"})}}
func(a *app)adjust(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodPost{httpx.JSON(w,405,map[string]string{"error":"method not allowed"});return};var in struct{ItemID int64 `json:"item_id"`;Delta float64 `json:"delta"`};if httpx.DecodeJSON(r,&in)!=nil||in.ItemID==0{httpx.JSON(w,400,map[string]string{"error":"item_id and delta required"});return};res,err:=a.db.Exec("UPDATE inventory_items SET stock=GREATEST(stock+?,0) WHERE id=?",in.Delta,in.ItemID);if err!=nil{httpx.JSON(w,500,map[string]string{"error":err.Error()});return};n,_:=res.RowsAffected();if n==0{httpx.JSON(w,404,map[string]string{"error":"item not found"});return};httpx.JSON(w,200,map[string]any{"item_id":in.ItemID,"adjusted_by":in.Delta})}
func(a *app)suppliers(w http.ResponseWriter,r *http.Request){switch r.Method{case http.MethodGet:rows,err:=a.db.Query("SELECT id,name,COALESCE(contact,''),COALESCE(phone,'') FROM suppliers ORDER BY name");if err!=nil{httpx.JSON(w,500,map[string]string{"error":err.Error()});return};defer rows.Close();out:=[]supplier{};for rows.Next(){var x supplier;if rows.Scan(&x.ID,&x.Name,&x.Contact,&x.Phone)==nil{out=append(out,x)}};httpx.JSON(w,200,out);case http.MethodPost:var x supplier;if httpx.DecodeJSON(r,&x)!=nil{httpx.JSON(w,400,map[string]string{"error":"invalid json"});return};res,err:=a.db.Exec("INSERT INTO suppliers(name,contact,phone) VALUES(?,?,?)",x.Name,x.Contact,x.Phone);if err!=nil{httpx.JSON(w,500,map[string]string{"error":err.Error()});return};x.ID,_=res.LastInsertId();httpx.JSON(w,201,x);default:httpx.JSON(w,405,map[string]string{"error":"method not allowed"})}}
func(a *app)summary(w http.ResponseWriter,_ *http.Request){var alerts,total int;_ = a.db.QueryRow("SELECT COUNT(*) FROM inventory_items WHERE stock<=reorder_level").Scan(&alerts);_ = a.db.QueryRow("SELECT COUNT(*) FROM inventory_items").Scan(&total);httpx.JSON(w,200,map[string]any{"inventory_alerts":alerts,"total_items":total})}
