package main

import("log";"net/http";"net/http/httputil";"net/url";"strings";"github.com/ditasetyakurniawan-droid/tropical-management-v1/internal/httpx";"github.com/golang-jwt/jwt/v5")
type gateway struct{secret []byte;routes []route};type route struct{prefix string;proxy *httputil.ReverseProxy}
func main(){g:=&gateway{secret:[]byte(httpx.Env("JWT_SECRET","local-dev-secret-change-this-value"))};g.routes=[]route{{"/api/auth",proxy(httpx.Env("AUTH_SERVICE_URL","http://auth-service:8080"))},{"/api/users",proxy(httpx.Env("AUTH_SERVICE_URL","http://auth-service:8080"))},{"/api/audits",proxy(httpx.Env("AUDIT_SERVICE_URL","http://audit-service:8080"))},{"/api/issues",proxy(httpx.Env("AUDIT_SERVICE_URL","http://audit-service:8080"))},{"/api/inventory",proxy(httpx.Env("INVENTORY_SERVICE_URL","http://inventory-service:8080"))},{"/api/suppliers",proxy(httpx.Env("INVENTORY_SERVICE_URL","http://inventory-service:8080"))},{"/api/sales",proxy(httpx.Env("SALES_SERVICE_URL","http://sales-service:8080"))},{"/api/dashboard",proxy(httpx.Env("DASHBOARD_SERVICE_URL","http://dashboard-service:8080"))}};mux:=http.NewServeMux();mux.HandleFunc("/healthz",func(w http.ResponseWriter,_ *http.Request){httpx.JSON(w,200,map[string]string{"status":"ok","service":"api-gateway"})});mux.Handle("/",g);log.Println("api-gateway listening on :8080");log.Fatal(http.ListenAndServe(":8080",mux))}
func proxy(raw string)*httputil.ReverseProxy{u,err:=url.Parse(raw);if err!=nil{panic(err)};return httputil.NewSingleHostReverseProxy(u)}
func(g *gateway)ServeHTTP(w http.ResponseWriter,r *http.Request){w.Header().Set("Access-Control-Allow-Origin",httpx.Env("CORS_ORIGIN","http://localhost:3000"));w.Header().Set("Access-Control-Allow-Headers","Authorization, Content-Type");w.Header().Set("Access-Control-Allow-Methods","GET,POST,PATCH,PUT,DELETE,OPTIONS");if r.Method==http.MethodOptions{w.WriteHeader(http.StatusNoContent);return};if r.URL.Path!="/api/auth/login"{claims,err:=g.claims(r);if err!=nil{httpx.JSON(w,401,map[string]string{"error":"unauthorized"});return};role,_:=claims["role"].(string);if !allowed(role,r.Method,r.URL.Path){httpx.JSON(w,403,map[string]string{"error":"forbidden for role "+role});return};r.Header.Set("X-User-Role",role)};for _,rt:=range g.routes{if strings.HasPrefix(r.URL.Path,rt.prefix){rt.proxy.ServeHTTP(w,r);return}};httpx.JSON(w,404,map[string]string{"error":"route not found"})}
func(g *gateway)claims(r *http.Request)(jwt.MapClaims,error){raw,err:=httpx.BearerToken(r);if err!=nil{return nil,err};t,err:=jwt.Parse(raw,func(*jwt.Token)(any,error){return g.secret,nil},jwt.WithValidMethods([]string{"HS256"}));if err!=nil||!t.Valid{return nil,jwt.ErrTokenInvalidClaims};c,ok:=t.Claims.(jwt.MapClaims);if !ok{return nil,jwt.ErrTokenInvalidClaims};return c,nil}
func allowed(role,method,path string)bool{if role=="admin"{return true};if method==http.MethodGet{return true};if role=="auditor"&&(strings.HasPrefix(path,"/api/audits")||strings.HasPrefix(path,"/api/issues")){return true};if role=="staff"&&strings.HasPrefix(path,"/api/sales"){return true};return false}
